log_level = "warn"
# outputs = { Targets = ["eDP-1"] }
outputs = "All"
position = "Top"
app_launcher_cmd = "walker"
enable_esc_key = true

[modules]
left = [ [ "appLauncher", "Updates", "Workspaces", "WindowTitle" ] ]
center = [ "Clock" ]
right = [ "SystemInfo", [ "Settings" ] ]


[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = 'alacritty -e bash -c "yay; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true
max_workspaces = 5
workspace_names = ["一","二","三","四","五","六","七","八","九","十",]
# workspace_names = ["","","","","","","","","","",]


[[CustomModule]]
name = "appLauncher"
icon = "󰣇"
command = "rofi -show drun"

[window_title]
mode = "Class"
truncate_title_after_length = 100

[settings]
lock_cmd = "playerctl --all-players pause; hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

[appearance]
style = "Solid"

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = [ "#7aa2f7", "#9ece6a" ]
special_workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"

